deployment:
  version: IMAGE_VERSION
  imageURL: 315069654700.dkr.ecr.us-east-1.amazonaws.com/expense/frontend
hpa:
  utilisation: 5
tgb: 
  arn:aws:elasticloadbalancing:us-east-1:339713002272:targetgroup/expense-dev/531dfb97722da3ab